import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF8EE',
  },
  glowOne: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 999,
    backgroundColor: '#FFE9D9',
    top: -140,
    left: -140,
    opacity: 0.65,
  },
  glowTwo: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: '#FFF3E4',
    bottom: 120,
    right: -90,
    opacity: 0.9,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 36,
    gap: 16,
  },
  topModeRow: {
    flexDirection: 'row',
    gap: 14,
    marginBottom: 2,
  },
  topModeTab: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8D9C8',
    paddingVertical: 12,
    backgroundColor: '#FFFDF8',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  topModeTabActive: {
    borderColor: '#E6762F',
    backgroundColor: '#FFE9D9',
  },
  topModeIcon: {
    color: 'rgba(0,0,0,0.58)',
    fontSize: 15,
    fontWeight: '800',
  },
  topModeIconActive: {
    color: '#B88A44',
  },
  topModeLabel: {
    color: 'rgba(0,0,0,0.58)',
    fontWeight: '700',
    fontSize: 13,
  },
  topModeLabelActive: {
    color: '#B88A44',
  },
  tabRow: {
    flexDirection: 'row',
    gap: 14,
  },
  manageSubTabRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
    marginBottom: 12,
  },
  tab: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 13,
    alignItems: 'center',
    backgroundColor: '#FFFDF8',
    borderWidth: 1,
    borderColor: '#E8D9C8',
  },
  tabActive: {
    backgroundColor: '#FFE9D9',
    borderColor: '#E6762F',
  },
  tabLabel: {
    fontWeight: '700',
    color: 'rgba(0,0,0,0.87)',
    fontSize: 16,
  },
  tabLabelActive: {
    color: '#B88A44',
  },
  randomStage: {
    minHeight: 640,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E8D9C8',
    backgroundColor: '#FFFDF8',
    padding: 20,
    justifyContent: 'space-between',
  },
  filterFab: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: '#FFF8EE',
    borderWidth: 1,
    borderColor: '#E8D9C8',
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  filterFabIcon: {
    color: '#B88A44',
    fontSize: 16,
    fontWeight: '900',
  },
  filterFabText: {
    color: '#3A403F',
    fontWeight: '700',
    fontSize: 14,
  },
  randomCenterWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 22,
  },
  randomFooterCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8D9C8',
    backgroundColor: '#FFF8EE',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  randomFooterKicker: {
    color: '#B88A44',
    fontWeight: '800',
    fontSize: 13,
  },
  randomFooterText: {
    color: 'rgba(0,0,0,0.62)',
    fontWeight: '600',
    fontSize: 13,
    lineHeight: 18,
  },
  randomFoodLoaderWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f4f7ff',
    borderWidth: 1,
    borderColor: '#c3cfdf',
  },
  randomFoodLoaderHidden: {
    opacity: 0,
  },
  randomFoodLoaderEmoji: {
    fontSize: 28,
  },
  randomBigButton: {
    width: 268,
    height: 268,
    borderRadius: 999,
    backgroundColor: '#FFE9D9',
    borderWidth: 2,
    borderColor: '#E6762F',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  randomBigButtonText: {
    color: '#3A403F',
    fontSize: 40,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  sectionCard: {
    backgroundColor: '#FFFDF8',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E8D9C8',
  },
  manageHeaderBar: {
    borderWidth: 1,
    borderColor: '#E8D9C8',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#FFF3E4',
    marginBottom: 12,
  },
  manageHeaderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  manageHeaderTitle: {
    color: '#3A403F',
    fontWeight: '800',
    fontSize: 24,
    lineHeight: 30,
    marginBottom: 4,
  },
  manageHeaderUser: {
    color: 'rgba(0,0,0,0.58)',
    fontWeight: '600',
    fontSize: 14,
  },
  logoutTextBtn: {
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  logoutText: {
    color: '#C43E2F',
    fontWeight: '800',
    fontSize: 14,
  },
  formTopBar: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 18,
    gap: 10,
  },
  formTopActions: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  typeChooserTop: {
    marginBottom: 16,
  },
  typeChooserTitle: {
    color: '#3A403F',
    fontWeight: '800',
    fontSize: 15,
    marginBottom: 8,
  },
  listTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 14,
  },
  listHeaderTitle: {
    fontWeight: '800',
    fontSize: 24,
    color: '#3A403F',
    lineHeight: 30,
  },
  button: {
    backgroundColor: '#FFE9D9',
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 999,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: '#E6762F',
    marginTop: 14,
  },
  buttonPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
  buttonDisabled: {
    opacity: 0.52,
  },
  buttonText: {
    color: '#3A403F',
    fontWeight: '800',
  },
  secondaryButton: {
    backgroundColor: '#FFFDF8',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8D9C8',
  },
  secondaryButtonMuted: {
    opacity: 0.9,
  },
  secondaryActive: {
    backgroundColor: '#FFE9D9',
    borderColor: '#E6762F',
  },
  secondaryDanger: {
    backgroundColor: '#FDF0EE',
    borderColor: '#D74A3A',
  },
  secondaryButtonText: {
    color: '#3A403F',
    fontWeight: '600',
  },
  authActionsRow: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 14,
    marginBottom: 14,
  },
  authActionButton: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
  },
  inlineActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    marginTop: 14,
    marginBottom: 14,
  },
  loader: {
    marginTop: 8,
  },
  error: {
    marginTop: 10,
    color: '#C43E2F',
    fontWeight: '700',
  },
  success: {
    marginTop: 10,
    color: '#2E7D32',
    fontWeight: '700',
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#3A403F',
    marginTop: 16,
    marginBottom: 12,
  },
  hintText: {
    fontSize: 14,
    color: 'rgba(0,0,0,0.58)',
    marginBottom: 8,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: '#E8D9C8',
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: '#FFFDF8',
    paddingLeft: 12,
    paddingRight: 8,
    minHeight: 58,
    position: 'relative',
  },
  inputRowMulti: {
    alignItems: 'flex-start',
    minHeight: 132,
  },
  inputControl: {
    flex: 1,
    color: 'rgba(0,0,0,0.87)',
    paddingVertical: 11,
  },
  inputControlMulti: {
    minHeight: 122,
    textAlignVertical: 'top',
  },
  inputClearBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(30, 57, 50, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.10)',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    alignSelf: 'center',
  },
  inputClearBtnMulti: {
    alignSelf: 'flex-start',
    marginTop: 12,
  },
  inputClearBtnText: {
    color: 'rgba(0,0,0,0.58)',
    fontWeight: '900',
    lineHeight: 24,
    fontSize: 20,
  },
  empty: {
    color: 'rgba(0,0,0,0.58)',
    marginTop: 6,
  },
  stateCard: {
    marginTop: 12,
    paddingHorizontal: 18,
    paddingVertical: 22,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8D9C8',
    backgroundColor: '#FFF8EE',
    alignItems: 'center',
    gap: 7,
  },
  stateEmoji: {
    fontSize: 30,
    marginBottom: 2,
  },
  stateTitle: {
    color: '#3A403F',
    fontWeight: '800',
    fontSize: 16,
    textAlign: 'center',
  },
  stateText: {
    color: 'rgba(0,0,0,0.58)',
    fontWeight: '600',
    lineHeight: 19,
    textAlign: 'center',
  },
  listCard: {
    backgroundColor: '#FFFDF8',
    borderRadius: 12,
    padding: 12,
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#E8D9C8',
  },
  archivedListCard: {
    backgroundColor: '#FFF8EE',
    borderStyle: 'dashed',
  },
  listCardTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  listCardTitle: {
    flex: 1,
    fontWeight: '800',
    fontSize: 16,
    color: '#3A403F',
  },
  listCardText: {
    marginTop: 4,
    color: 'rgba(0,0,0,0.58)',
  },
  metadataRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 7,
  },
  metadataText: {
    marginTop: 5,
    color: 'rgba(0,0,0,0.50)',
    fontWeight: '600',
    fontSize: 12,
  },
  archivedMeta: {
    marginTop: 4,
    color: '#B88A44',
    fontWeight: '700',
    fontSize: 12,
  },
  typeBadge: {
    overflow: 'hidden',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: '#FFE9D9',
    color: '#9A612F',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  lockedAction: {
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#F5EFE7',
  },
  lockedActionText: {
    color: 'rgba(0,0,0,0.48)',
    fontWeight: '700',
    textAlign: 'center',
  },
  inlineLoading: {
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#FFF3E4',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  inlineLoadingText: {
    color: '#9A612F',
    fontWeight: '700',
  },
  ownerNotice: {
    marginTop: 12,
    marginBottom: 4,
    borderRadius: 14,
    padding: 13,
    backgroundColor: '#FFF3E4',
    borderWidth: 1,
    borderColor: '#E8D9C8',
  },
  ownerNoticeTitle: {
    color: '#9A612F',
    fontWeight: '800',
    marginBottom: 3,
  },
  ownerNoticeText: {
    color: 'rgba(0,0,0,0.60)',
    fontWeight: '600',
    lineHeight: 18,
  },
  keyboardWrap: {
    flex: 1,
  },
  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  selectedDishSheet: {
    maxHeight: '88%',
    backgroundColor: '#FFFDF8',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderWidth: 1,
    borderColor: '#E8D9C8',
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 16,
  },
  selectedSheetHandle: {
    alignSelf: 'center',
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#D3DDE9',
    marginBottom: 10,
  },
  selectedSheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  selectedSheetBody: {
    paddingBottom: 30,
  },
  card: {
    marginTop: 18,
    backgroundColor: '#FFFDF8',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E8D9C8',
  },
  cardTitle: {
    fontSize: 21,
    fontWeight: '800',
    marginBottom: 8,
    color: '#3A403F',
  },
  description: {
    color: 'rgba(0,0,0,0.58)',
    marginBottom: 12,
  },
  sectionTitle: {
    marginTop: 6,
    marginBottom: 6,
    fontWeight: '800',
    fontSize: 18,
    color: '#3A403F',
  },
  listItem: {
    color: 'rgba(0,0,0,0.87)',
    marginBottom: 4,
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.32)',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  sheetCard: {
    backgroundColor: '#FFFDF8',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E8D9C8',
    padding: 16,
    gap: 8,
  },
  confirmCard: {
    backgroundColor: '#FFFDF8',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E8D9C8',
    padding: 18,
  },
  confirmKicker: {
    color: '#B88A44',
    fontWeight: '800',
    fontSize: 13,
    marginBottom: 7,
  },
  confirmTitle: {
    color: '#3A403F',
    fontWeight: '900',
    fontSize: 21,
    marginBottom: 8,
  },
  confirmText: {
    color: 'rgba(0,0,0,0.58)',
    fontWeight: '600',
    lineHeight: 20,
  },
  confirmActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 18,
  },
  sheetTitle: {
    color: '#3A403F',
    fontWeight: '800',
    fontSize: 18,
    marginBottom: 4,
  },
  sheetButton: {
    borderRadius: 10,
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E8D9C8',
    backgroundColor: '#FFFDF8',
  },
  sheetButtonActive: {
    borderColor: '#E6762F',
    backgroundColor: '#FFE9D9',
  },
  sheetButtonText: {
    color: '#3A403F',
    fontWeight: '700',
  },
  sheetCloseButton: {
    marginTop: 4,
    paddingVertical: 10,
    alignItems: 'center',
  },
  sheetCloseText: {
    color: '#B88A44',
    fontWeight: '700',
  },
  toastWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 24,
    alignItems: 'center',
  },
  toastCard: {
    backgroundColor: 'rgba(60, 22, 10, 0.92)',
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8D9C8',
    maxWidth: '100%',
  },
  toastText: {
    color: '#FFF4E8',
    fontWeight: '700',
    textAlign: 'center',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#FFF8EE',
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#D3DDE9',
  },
  modalHeaderTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#3A403F',
  },
  modalCloseButton: {
    borderWidth: 1,
    borderColor: '#E8D9C8',
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 12,
    backgroundColor: '#FFFDF8',
  },
  modalCloseText: {
    color: '#3A403F',
    fontWeight: '700',
  },
  modalContent: {
    padding: 16,
    gap: 12,
  },
  modalDishTitle: {
    color: '#3A403F',
    fontSize: 30,
    fontWeight: '900',
  },
  modalInfoBlock: {
    backgroundColor: '#FFFDF8',
    borderWidth: 1,
    borderColor: '#E8D9C8',
    borderRadius: 16,
    padding: 14,
  },
  modalType: {
    color: '#3A403F',
    fontWeight: '700',
    marginBottom: 6,
  },
});
